---
version: "3"

services:
  
  api:
    build:
      context: api/.
    command: uvicorn api:app --port 8888 --host 0.0.0.0 --reload
    ports:
      - "8888:8888"
    volumes:
      - ./api/:/app
    environment:
      ENVIRONMENT: development
      PORT: 8888
      
  frontend:
    build:
      context: frontend/.
    depends_on: 
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    env_file: 
      - frontend/.env

  bot:
    build:
      context: bot/.
    restart: always
    depends_on: 
      - api
    volumes:
      - ./bot:/app
    env_file:
      - bot/.env