# flake8: noqa
from datetime import datetime

# All quotes were extracted from http://www.citador.pt/frases/citacoes/a/gustavo-santos/1
QUOTES = {
    0: "O \xfanico pre\xe7o da tua liberdade \xe9 a responsabilidade que tens por escolheres us\xe1-la.",
    1: "Assim como os confiantes atraem os confiantes, os invejosos, rancorosos e maldosos tamb\xe9m se atraem uns aos outros.",
    2: "Quem pensa por si, afirma o que sente e materializa as suas vontades, ser\xe1 sempre controverso, mas \xe9 precisamente da controv\xe9rsia que nasce a mudan\xe7a, \xe9 do desacordo que se d\xe1 a evolu\xe7\xe3o da alma.",
    3: "A liberdade \xe9 o expoente m\xe1ximo do amor-pr\xf3prio.",
    4: "S\xf3 aquele que ousa, por sua livre e espont\xe2nea vontade, abandonar o rebanho da indol\xeancia para fazer o seu pr\xf3prio destino \xe9 que alcan\xe7ar\xe1, verdadeiramente, o total poder da alma que \xe9.",
    5: "N\xe3o te queixes da vida, n\xe3o fiques \xe0 espera dela, cria-a, e ter\xe1s a vida que sempre sonhaste.",
    6: "Uma pessoa que n\xe3o sonha n\xe3o encontra motivos, realmente fortes, para acordar todas as manh\xe3s com vontade de viver, n\xe3qo se conecta com a divindade em si mesma.",
    7: "A vida \xe9 uma troca, como tal, tens de saber trocar o melhor de ti com o melhor dos outros e nunca o melhor que tens com o pior do que t\xeam para ti.",
    8: "A tua energia \xe9 como uma carteira de a\xe7\xf5es: deves saber investi-la, aument\xe1-la e depois partilh\xe1-la.",
    9: "Uma pessoa que n\xe3o se ama d\xe1 um trabalho do cara\xe7as. N\xe3o se entrega, sente pela metade, duvida, cobra, culpa, desconfia e ainda se vitima. Repito, algu\xe9m no seu perfeito ju\xedzo escolhe esse padr\xe3o de pessoa para se relacionar?",
    10: "A dor do futuro \xe9 o sofrer por antecipa\xe7\xe3o, de todas as dores a mais rid\xedcula.",
    11: "Quanto mais dependeres do destino e mais te relacionares com gente dependente do destino, mais longe te encontras de sentir, da entrega e da vida na verdadeira ace\xe7\xe3o da palavra. Quanto mais do pior, menos do melhor. O teu destino \xe9 aquilo que tu pensas, aquilo que tu desejas para ti e te permites sentir, mas tamb\xe9m pode ser aquilo que nunca ou jamais acreditar\xe1s vir a conquistar ou a sentir.",
    12: "A maior parte da ansiedade que sentes \xe9 devida a uma mente obstru\xedda por problemas, incapaz de te obedecer e com uma capacidade tremenda de inventar cen\xe1rios sombrios.",
    13: "O futuro existe, sim, mas na nossa mente. Em mais lado nenhum. Como tal, e como em todos os outros tempos, devemos estar atentos \xe0 forma como ele nos Mente, Manipula e Maltrata, por forma a minimizarmos os estragos que, naturalmente, ir\xe3o existir.",
    14: "Um presente poderoso \xe9 a soma de v\xe1rias consci\xeancias. Escolhe as pessoas certas para caminharem contigo e expulsa as que te limitam, aprende a amar-te para que te consigas desprender do ego e permite que a paix\xe3o tome conta de ti, para que te possas libertar da rotina.",
    15: "Todas as armadilhas do presente s\xe3o escolhidas por ti, \xe9s tu que lhes d\xe1s esse significado e lhes prestas tamanha vassalagem, portanto, \xe9s tu o \xfanico e verdadeiro respons\xe1vel por cair nelas, por te afundares numa profunda mis\xe9ria emocional e por deixares de sentir o que verdadeiramente pode e deve ser sentido.",
    16: "Se \xe9 a tua vida tens de ser tu a querer o melhor para ela e muito passa pelas pessoas que est\xe3o ou podem estar ao teu lado. Qualquer tipo de rela\xe7\xe3o que tenhas s\xf3 faz sentido se ganhares alguma coisa com ela, mas alguma coisa boa e que se sinta, sen\xe3o n\xe3o \xe9 uma rela\xe7\xe3o, \xe9 uma obriga\xe7\xe3o.",
    17: "A dor do presente \xe9 uma conflu\xeancia de desilus\xf5es e ansiedades, de bloqueios e de medos, de tudo o que aconteceu ou ficou por acontecer e de tudo o que poder\xe1 acontecer ou nunca existir.",
    18: "A mente serve para filtrar o cora\xe7\xe3o, n\xe3o para o aprisionar, mas tamb\xe9m nos serve, e bem, se estiver apontada para a criatividade e domesticada para nos permitir sentir.",
    19: "Acredita em ti, hoje e sempre, e nunca te esque\xe7as que sempre que te desvias um cent\xedmetro daquilo que desejas vais sempre parar a quil\xf3metros de dist\xe2ncia daquilo que \xe9s.",
    20: "Algu\xe9m acha que conquistei a minha felicidade atrav\xe9s de um jogo qualquer ou que a ganhei numa rifa? A minha felicidade foi conquistada a pulso, com muitas l\xe1grimas, com muitas cabe\xe7adas na parede, muitas quedas e muitos enganos, muitas m\xe1s escolhas e sofrimento \xe0 mistura. N\xe3o se escala uma montanha sem tombar algumas vezes.",
    21: "Uma pessoa equilibrada n\xe3o sente necessidade de julgar seja quem for, pois n\xe3o depende desse requinte de malvadez que \xe9 a sobreposi\xe7\xe3o perante o outro.",
    22: "Quem sabe de si sabe sempre expor-se de uma forma afirmativa sem nunca necessitar de se impor aos demais.",
    23: "A verdade abana qualquer um porque nos habitu\xe1mos a viver na mentira.",
    24: "O \xfaltimo desejo de uma pessoa feliz \xe9 ser dona da raz\xe3o, n\xe3o precisa, pois a sua basta-lhe para inspirar todos os que a rodeiam.",
    25: "Se queres expandir o que sentes, se queres partilhar com os outros e com o mundo as ideias que tens, e se queres inspirar quem te rodeia, f\xe1-lo de forma afirmativa, mas nunca, nunca mesmo, atinjas seja quem for para chegares onde queres chegar ou para justificar onde nunca chegaste.",
    26: "As pessoas dependem do gosto dos outros por si mesmas porque n\xe3o gostam delas pr\xf3prias e sentem uma enorme necessidade de estarem consecutivamente rodeadas de gente amiga para que n\xe3o tenham de lidar com a voz inimiga que mora dentro delas.",
    27: "Quanto mais te queixares menos respeito ter\xe1s.",
    28: "Sempre que assumimos a nossa verdade perante seja quem for e em que circunst\xe2ncias for estamos mais perto, muito mais perto, de ganhar o merecido respeito que todos os seres humanos deviam sentir uns pelos outros.",
    29: "Ningu\xe9m \xe9 manipulado ou subjugado quando acredita fortemente naquilo que sente, pelo contr\xe1rio quem n\xe3o se permite sentir, ou seja, quem n\xe3o se permite viver nada sabe, nada conhece e em nada acredita, logo \xe9 jogado de p\xe9 para p\xe9 pelos mais espertos e perigosos egos.",
    30: "Apenas a verdade carrega consigo a for\xe7a transformadora capaz de levar seja quem for \xe0 a\xe7\xe3o.",
    31: "Toda e qualquer pessoa com um padr\xe3o comportamental assente na vitimiza\xe7\xe3o agir\xe1 sempre de forma a que tu acredites que a magoaste ou atacaste para que imediatamente a seguir te sintas culpado, te vulnerabilizes e por fim recues com a tua palavra e ainda pe\xe7as desculpa.",
    32: "N\xe3o esperes nunca sensibilizar ou gerar identifica\xe7\xe3o em algu\xe9m se n\xe3o falares sobre ti mesmo, se n\xe3o te expuseres ao erro e se n\xe3o partilhares o segredo que tu pr\xf3prio desvendaste para superar um qualquer problema.",
    33: "O peso das palavras n\xe3o ditas \xe9 mais pesado e doloroso que a pr\xf3pria cruz.",
    34: "Um assunto por resolver \xe9 uma esp\xe9cie de m\xe1quina do tempo de apenas um bot\xe3o e que te permite unicamente regressar ao passado e multiplic\xe1-lo infinitas vezes no teu presente.",
    35: "O resultado de uma vida em sil\xeancio \xe9, mais tarde ou mais cedo, uma indisposi\xe7\xe3o constante que levar\xe1 o seu hospedeiro a vomitar todas as emo\xe7\xf5es apodrecidas durante anos e anos na cara dos outros, como se os outros fossem os verdadeiros culpados dessa agonia.",
    36: "O medo de magoar os outros \xe9 facilmente ultrapass\xe1vel se garantirmos que a nossa comunica\xe7\xe3o se baseia, \xfanica e exclusivamente, na verdade.",
    37: "O medo de dizer o que sentimos \xe9 uma granada sem cavilha, ou seja, pode explodir a qualquer momento e os \xfanicos lesados somos n\xf3s.",
    38: "Ainda que verdadeira para n\xf3s, uma simples frase mal medida aliada \xe0 crueldade de uma express\xe3o facial sem qualquer esp\xe9cie de piedade, pode causar danos irrevers\xedveis numa pessoa que j\xe1 se encontra fragilizada pela sua realidade atual.",
    39: "N\xf3s somos o que sentimos e n\xe3o o que temos e a maior prova disso \xe9 que as melhores sensa\xe7\xf5es que podemos viver s\xe3o todas \xe0 borla.",
    40: "N\xe3o h\xe1 desvantagem maior que a coloca\xe7\xe3o das palavras e dos pensamentos dos outros \xe0 frente das nossas ideias, dos nossos prazeres e da nossa realidade.",
    41: "Um homem sozinho n\xe3o consegue mudar o mundo, mas pode come\xe7ar. Se eu come\xe7ar deste lado e tu desse, chegar\xe1 o dia em que nos vamos encontrar e a\xed n\xe3o seremos dois, seremos todos aqueles que eu e tu conseguimos inspirar.",
    42: "Para ser como os outros prefiro assumir que n\xe3o sou ningu\xe9m.",
    43: "Energia atrai energia. Se \xe9s tonto atrais pessoas tontas; se \xe9s afetuoso atrais pessoas afetuosas; e se tens medo atrais mais motivos para continuares a t\xea-lo.",
    44: "Uma vez encontrada a felicidade ela precisa de ser expandida e partilhada, se n\xe3o acabar\xe1 por so\xe7obrar.",
    45: "N\xe3o interessa a forma como os outros reagem, interessam sim as tuas a\xe7\xf5es e o incondicionalismo que nelas empregas.",
    46: "Aquilo em que acreditamos s\xf3 tem o poder de inspirar se o verbalizarmos ou colocarmos em a\xe7\xe3o.",
    47: "A solid\xe3o n\xe3o \xe9 e nunca ser\xe1 a aus\xeancia dos outros, mas sim a falta que te fazes a ti pr\xf3prio.",
    48: "N\xe3o h\xe1 ningu\xe9m que coloque os outros \xe0 sua frente e n\xe3o seja consecutivamente sovado. Ningu\xe9m.",
    49: "O medo \xe9 o grande respons\xe1vel pelas palavras que n\xe3o te saem pela boca, pelas letras que engoles a seco e pela consequente asfixia que te matar\xe1 lenta e dolorosamente.",
    50: "Quando descobrires que mandas em ti e que a tua boca \xe9 um canal de verdade, descobres as fraquezas dos outros e passas a domin\xe1-los em qualquer situa\xe7\xe3o.",
    51: "N\xe3o \xe9 poss\xedvel ajudar ou proteger ningu\xe9m por quem se sinta pena. A pena adormece as pessoas, \xe9 como uma anestesia geral que imobiliza o corpo por tempo indeterminado. Ao inv\xe9s, a assertividade das palavras abana-as, desperta-as e, quase sempre, devolve-lhes o poder de agir. Mexe com elas e ela mexem-se a seguir.",
    52: "A confian\xe7a \xe9 o motor que nos faz ir mais longe e com menor desgaste, \xe9 ela que facilmente nos catapulta para uma dimens\xe3o superior onde nos \xe9 poss\xedvel olhar para a nossa vida de um ponto de vista mais alto, logo, mais consciente, assertivo e de melhores escolhas.",
    53: "N\xe3o h\xe1 ressurrei\xe7\xe3o sem confian\xe7a e muito menos felicidade se n\xe3o confiares em ti.",
    54: "Quem acredita que \xe9 o que sai da boca dos outros morrer\xe1 encharcado em tanto mau h\xe1lito.",
    55: "\xc9 a pregui\xe7a que torna as pessoas m\xe1s. Sim, m\xe1s, horr\xedveis e est\xfapidas. E porqu\xea? Simples, porque vivem totalmente alienadas de quem s\xe3o para viverem, por inveja ou ci\xfame ou maldade, a exist\xeancia dos outros.",
    56: "Quando escreves a tua verdade, ficas mais perto de a viver e \xe9 por isso que \xe9 t\xe3o importante comprometeres-te.",
    57: "Se h\xe1 gente perigosa, \xe9 gente dominada pelo ego.",
    58: "Existe sempre uma verdade dentro de n\xf3s e ela nunca passa pela mente.",
    59: "A intui\xe7\xe3o gera vida, faz-nos acreditar para l\xe1 do impens\xe1vel e a mente castra-nos a esperan\xe7a porque nunca nos liberta do pensamento.",
    60: "Identificar o que nos limita e enfrentar a limita\xe7\xe3o s\xe3o as \xfanicas premissas capazes de nos conduzir \xe0 salva\xe7\xe3o e s\xe3o siamesas, pois quem identifica e n\xe3o enfrenta viver\xe1 eternamente assombrado pelo que podia ter feito e nunca fez.",
    61: "A confian\xe7a mora em cada esquina, s\xf3 tens de escolher dobr\xe1-la.",
    62: "Apenas a entrega pode fazer de ti algu\xe9m bom a fazer alguma coisa bem e eu entrego-me. S\xf3 sei viver assim.",
    63: "Sempre que nos queixamos, investimos grandes doses de energia no lado errado da aposta e depois, l\xe1 est\xe1, toldamos, enfezamos e desistimos.",
    64: "As palavras certas no momento certo em que s\xe3o sentidas conseguem mudar vidas.",
    65: "Se n\xe3o regarmos uma flor com a devida frequ\xeancia, o que acontece? Ela desata a murchar e acaba por morrer, certo? O mesmo se passa com as pessoas. Se n\xe3o adicionarem as por\xe7\xf5es necess\xe1rias de experi\xeancia, de risco ou desafios e de momentos de paix\xe3o aos seus dias, tamb\xe9m elas v\xe3o acabar por perder o brilho, emurchecer e morrer.",
    66: "Perder ou desconsiderar o contacto com a nossa crian\xe7a interior \xe9 negligenciar a nossa intui\xe7\xe3o, a nossa verdadeira sabedoria e abrir m\xe3o de tudo o que \xe9 melhor para n\xf3s.",
    67: "As for\xe7as nunca nos faltam quando queremos muito uma coisa.",
    68: "Nenhuma dor f\xedsica \xe9 t\xe3o violenta como aquela que se sente nas emo\xe7\xf5es atrav\xe9s da mente.",
    69: "Costuma dizer-se que um amor cura-se com outro, eu prefiro receitar a paix\xe3o. Os efeitos s\xe3o mais eficazes. Mais prazer e mais depressa. Mais confian\xe7a em menos tempo.",
    70: "Os relacionamentos s\xf3 fazem sentido quando ambas as partes potenciam a outra. Quando isso deixa de acontecer, quando o dar e receber cessa, e se perde a identifica\xe7\xe3o, a paix\xe3o esgota-se e d\xe1 lugar \xe0 culpa.",
    71: "A paix\xe3o \xe9 o combust\xedvel da vida. Se te faltar n\xe3o chegas a lado nenhum.",
    72: "S\xf3 consegues ser confiante se sentires paix\xe3o pela vida.",
    73: 'Sair da zona de conforto \xe9 romper com um h\xe1bito, \xe9 escolher deixar de ser um "robot" que, independentemente dos est\xedmulos ou novas oportunidades atua sempre da mesma maneira, para voltarmos a ser humanos.',
    74: "\xc9 a mudan\xe7a que nos faz alcan\xe7ar novos mundos, \xe9 a descoberta que nos devolve o sentir.",
    75: "N\xe3o podemos atribuir \xe0 sorte ou ao azar a vida em que vivemos, temos de nos responsabilizar, de olhar bem para dentro e perceber a forma como pensamos e posteriormente agimos. N\xe3o h\xe1 sensa\xe7\xf5es quando nos acostumamos, quando repetimos hoje, amanh\xe3 e sempre o mesmo procedimento.",
    76: "Diferentes significados geram diferentes vidas e \xe9 fundamental que consigamos sempre descobrir o ouro por entre a lama. Sobrevalorizar um resultado negativo \xe9 sempre subvalorizar uma experi\xeancia que pode ter sido altamente positiva e, quem sabe, determinante para o resto da nossa vida.",
    77: "A confian\xe7a s\xf3 pode ser resgatada ao medo atrav\xe9s da experi\xeancia, do risco associado \xe0 sa\xedda da zona de conforto e da paix\xe3o!",
    78: "Uma pessoa sem confian\xe7a \xe9 sistematicamente esfrangalhada, violentada e reprimida at\xe9 apodrecer.",
    79: "Sempre que confias em ti \xe9s respeitado pelos outros. \xc9 uma li\xe7\xe3o de vida. E sabes porqu\xea? Porque poucos confiam, logo, querem ser como tu.",
    80: "Tudo o que te disseres de bom ou de mau ser\xe1 levado a s\xe9rio por ti, portanto muita aten\xe7\xe3o ao di\xe1logo interno que tens contigo, ele pode potenciar-te ou estar sistematicamente a envenenar-te.",
    81: "A verdadeira confian\xe7a \xe9 transmitida pelo que a pessoa \xe9 no seu \xedntimo e nunca pelo que ela tem ou faz.",
    82: "Uma pessoa confiante depende exclusivamente de si, pois tem a igni\xe7\xe3o da mente e a for\xe7a motriz do cora\xe7\xe3o a puxar para o mesmo lado. Nenhuma subida \xe9 imposs\xedvel, nenhum obst\xe1culo \xe9 intranspon\xedvel, nenhum sonho \xe9 inalcan\xe7\xe1vel.",
    83: "A assertividade serve para despertar, nunca para desrespeitar e n\xf3s estamos c\xe1 para inspirar, nunca para pisar.",
    84: "Ser assertivo \xe9 ser coerente \xe0 letra com aquilo que pensamos e sentimos, e afirm\xe1-lo sem apelo nem agravo, sem falsos moralismos nem pena de ningu\xe9m, apenas e somente porque nos respeitamos.",
    85: "\xc9 quando estamos equilibrados que o mundo nos parece mesmo redondo, sem bicos nem escamas, e que as pessoas nos parecem mesmo humanas onde o erro e a imperfei\xe7\xe3o fazem parte de um todo t\xe3o natural como a supera\xe7\xe3o e a bondade.",
    86: "N\xe3o h\xe1 caminho que resista sem momentos de celebra\xe7\xe3o. S\xe3o eles o t\xf3nico para mantermos um ritmo consistente de passada e o foco onde queremos chegar. (...) Celebrar \xe9 caminhar.",
    87: "A idade da nossa consci\xeancia simplifica muitas coisas e atalha sobretudo a dor. Ainda bem. Que nunca deixemos morrer a crian\xe7a interior que mora em n\xf3s.",
    88: "\xc9 incr\xedvel como, sendo a mesma pessoa, nos tornamos pessoas t\xe3o opostas se escolhermos dar predomin\xe2ncias diferentes ao pensar ou ao sentir.",
    89: "Quando amas, aprendes a deixar ir e depois apercebes-te que o verdadeiro amor tamb\xe9m passa por isso mesmo.",
    90: "Muitas vezes a antecipa\xe7\xe3o da dor \xe9 muito mais dolorosa que a viv\xeancia da mesma no momento em que ela est\xe1 a acontecer.",
    91: "\xc9 isto o amor. \xc9 preciso saber viv\xea-lo e depois saber do\xe1-lo. Quem o quer exclusivamente para si n\xe3o sente amor, mas posse, e o amor n\xe3o se consegue possuir. \xc9 imposs\xedvel. Ele \xe9 livre como uma andorinha e quem o quiser agarrar nunca saber\xe1 o que ele \xe9.",
    92: "Todas as respostas acabam por ser simples quando temos a habilidade de nos desobstruir dos pensamentos. Sempre que sentimos, a sabedoria maior flui, os reencontros sucedem-se e os maiores segredos s\xe3o revelados.",
    93: "Este \xe9 um dos mais valiosos passos do meu caminho: acreditar que nada morre, mesmo que desapare\xe7a da vista, e que nada se aparta do cora\xe7\xe3o se nos mantivermos ligados \xe0 ess\xeancia.",
    94: "Uma pessoa que saiba que vai morrer sabe que tem de viver. Esse \xe9, ali\xe1s, um dos grandes desafios da humanidade. Ter a consci\xeancia do fim, para que todos os momentos sejam o princ\xedpio de alguma coisa e todos sabemos como tudo \xe9 sempre mais saboroso no in\xedcio seja do que for.",
    95: "A responsabilidade d\xe1-nos sentido \xe0 vida.",
    96: "A inspira\xe7\xe3o d\xe1-se quando te permites ser.",
    97: "Ficamos sempre em paz quando nos falamos e depois decidimos.",
    98: "Quem escolhe \xe9 quem comanda, \xe9 quem decide, e n\xe3o h\xe1 um caminho bem feito sem erros nem in\xfameras tentativas.",
    99: "\xc9 quando assumimos as nossas escolhas que a nossa vida ganha \xe2nimo e fulgor.",
    100: "Ningu\xe9m pode ou tem o direito de obrigar algu\xe9m a fazer seja o que for. Apesar de renascermos juntos, cada um tem o seu processo, o seu n\xedvel de consci\xeancia e o livre arb\xedtrio para agir como entender.",
    101: "O mau trato e a indiferen\xe7a dos outros s\xe3o pontes para o nosso amor-pr\xf3prio. \xc9 com eles que nos \xe9 ensinado que dependemos, unicamente, de n\xf3s para sermos amados.",
    102: "Uma pessoa \xe9 sempre a representa\xe7\xe3o de pelo menos uma oportunidade para n\xf3s, implique ela a necessidade de experimentar o perd\xe3o ou aceita\xe7\xe3o, o amor ou a paix\xe3o.",
    103: "N\xe3o interessa as tormentas que passaram nem as tempestades que est\xe3o para vir. S\xf3 o momento onde est\xe1s \xe9 relevantes. Mas s\xf3 \xe9 poss\xedvel usufruir de tamanho privil\xe9gio quando temos tudo resolvido e o medo n\xe3o \xe9 suficientemente letal para nos congelar. S\xf3 \xe9 poss\xedvel viver assim quando desligamos a cabe\xe7a do passado e do futuro.",
    104: "Ningu\xe9m pode fazer por algu\xe9m o que essa pessoa n\xe3o faz por si.",
    105: "\xc9 incr\xedvel o que uma casa de banho pode fazer por uma pessoa. Algumas das minhas melhores ideias e algumas das minhas mais importantes descobertas foram mesmo vividas dentro de uma.",
    106: "Ser incondicional \xe9 fazer as coisas por n\xf3s, mas de forma que os outros possam usufruir delas sem que precisemos que depois nos compensem, reconhe\xe7am ou validem o que quer que seja. Fazemos por n\xf3s, porque nos apetece e, quando assim \xe9, n\xe3o existem cobran\xe7as, expectativas nem falsas ideias de que n\xe3o vale a pena. Vale sempre a pena quando temos vontade.",
    107: "Quem ama aceita todas as escolhas do seu amor, por muita dor que nos tragam.",
    108: "\xc9 triste, mas \xe9 maioritariamente isso que as pessoas fazem. Fazem pelos outros em vez de tentarem descobrir tudo o que podem ganhar dentro delas e depois cobram-lhes aten\xe7\xe3o, palavras, respostas e conversas.",
    109: "H\xe1 muito mais por aprender. N\xe3o podemos ficar agarrados a um momento e julgarmo-nos eternamente por isso. Se o fizermos, estaremos consecutivamente a negar novas li\xe7\xf5es e a\xed o fim n\xe3o ser\xe1 risonho. Imposs\xedvel. Nenhuma alma \xe9 feliz quando o corpo ou a mente se castram.",
    110: "Dar j\xe1 \xe9 receber, as pessoas \xe9 que s\xf3 acreditam naquilo que veem e n\xe3o d\xe3o um passo se n\xe3o visualizarem o que podem receber em troca.",
    111: "Podem at\xe9 existir caminhos onde a solid\xe3o seja uma via vi\xe1vel, mas n\xe3o h\xe1 veredas como aquelas em que as m\xe3os s\xe3o dadas, os afetos sentidos e o calor humano multiplicado.",
    112: "Somos todos respons\xe1veis uns pelos outros e se n\xe3o te responsabilizas, se n\xe3o d\xe1s o teu melhor, a culpa engolir-te-\xe1 mais cedo ou mais tarde.",
    113: "No momento em que nos soubermos respeitar, saberemos respeitar os outros. Somos todos mestres. Temos todos muitas li\xe7\xf5es para dar, in\xfameros contributos para doar at\xe9 chegar a nossa hora.",
    114: "Um velho, tal como um rec\xe9m-nascido, \xe9 a natureza no seu estado mais puro, \xe9 a prova de que o ciclo da vida existe mesmo e \xe9 um professor, gratuito e incondicional, para todos os que escolherem sentar-se \xe0 sua beira, ouvi-lo e interessar-se pela mat\xe9ria da alma.",
    115: "N\xe3o se pode mudar ningu\xe9m, s\xf3 n\xf3s mesmos. Ningu\xe9m \xe9 como n\xf3s, como tal jamais poderemos exigir que os outros tenham as atitudes que n\xf3s ter\xedamos. N\xe3o estamos dentro das suas peles, n\xe3o conhecemos a fundo as suas hist\xf3rias, os traumas adquiridos nem as incapacidades que os toldaram.",
    116: "O mais dif\xedcil em qualquer caminhada \xe9 dar o primeiro passo. Uma vez consumado, tudo conspira a nosso favor, inclusivamente n\xf3s mesmos.",
    117: "Quando queremos muito uma coisa e temos a coragem no sangue, o mundo inteiro pode cair que n\xf3s mantemo-nos de p\xe9.",
    118: "\xc9 o amor, ou a falta dele, que rege o mundo. Nada de bom acontece na sua aus\xeancia e todos os passos que possam ser dados sem o seu cunho ser\xe3o passos em falso.",
    119: "O amor n\xe3o \xe9 para ser julgado, \xe9 para ser vivido, venha ele de onde vier.",
    120: "Os velhos j\xe1 foram loucos, j\xe1 foram rebeldes, j\xe1 foram gente. E continuam a s\xea-lo, a malta \xe9 que os v\xea como plantas ca\xeddas. Se te permitires escut\xe1-los e lhes deres tempo de antena na emiss\xe3o da tua vida, n\xe3o te arrepender\xe1s.",
    121: "A malta nova tem a tend\xeancia de acreditar que os velhos foram sempre velhos, seres incapacitados de sentir e de viver as maiores loucuras \xe0 face da terra por amor. Mentira. Aquelas mem\xf3rias fervem de imagens vividas, de momentos inesquec\xedveis e de hist\xf3rias em que ningu\xe9m acreditaria.",
    122: "N\xe3o poder mudar as pessoas \xe9 um facto demasiado incontorn\xe1vel para lutarmos pelo contr\xe1rio. Temos de aceitar as pessoas como elas s\xe3o. Por muito que nos custe, por muito que as vejamos a morrer lentamente ou a afastarem-se cada vez mais da sua divindade, temos de aceit\xe1-las. Pelo nosso bem temos de aceit\xe1-las.",
    123: "Para perceberes tudo o que existe para l\xe1 do \xf3bvio, \xe9 necess\xe1rio estares atento aos sinais e que te permitas sentir para l\xe1 do normal. E isso s\xf3 \xe9 poss\xedvel se te alienares da mat\xe9ria da mente e da racionalidade do que v\xeas e do que ouves.",
    124: "Quando nos expressamos em amor, conectamo-nos \xe0 nossa energia de origem e \xe9 a\xed que nos lembramos de quem verdadeiramente somos e de que somos para sempre.",
    125: "\xc9 sempre assim: se for\xe7as uma descoberta interna, a mente obstrui-te logo a seguir. Tudo o que \xe9 sentido tem um momento certo, se ainda n\xe3o chegou \xe9 porque ainda n\xe3o \xe9 suposto chegar e de nada adianta for\xe7ar, pois ficar\xe1s cada vez mais e mais confuso.",
    126: "Quando damos valor ao que aparentemente n\xe3o tem valor nenhum, acabamos sempre por encontrar algo de valioso.",
    127: "O amor, seja por quem for ou em que circunst\xe2ncias, deveria estar imune a qualquer culpa e a qualquer atrito. Acredito profundamente que quando se ama, \xe9 largada para o ar  que todos respiramos uma esp\xe9cie de energia capaz de contagiar gente que acabou de se conhecer, e de todas as partes do mundo, ao ponto de transformar as suas indecis\xf5es em a\xe7\xf5es.",
    128: "A energia do amor \xe9 algo que n\xe3o \xe9 compar\xe1vel a mais nada e, por mais que dividisse a \xe1gua que tinha no copo e a partilhasse com mais e mais pessoas, sentia-o sempre cheio. A fonte divina, desde que estejas em contacto com ela, \xe9 inesgot\xe1vel.",
    129: "Temos todas as respostas em n\xf3s e se ainda n\xe3o as tivermos \xe9 porque ainda n\xe3o fizemos as perguntas certas.",
    130: "Quem sabe interpretar a natureza reconhece-lhe todo o poder de cura que tem.",
    131: "\xc9 inacredit\xe1vel como a vida nos mostra sempre, e das mais variadas maneiras, que nunca sabemos se estamos preparados para tudo.",
    132: "\xc9 a vitimiza\xe7\xe3o que corr\xf3i o mundo e a pregui\xe7a que lhe ateia fogo.",
    133: "\xc9 esta a minha rela\xe7\xe3o com as palavras. Ao mesmo tempo que as liberto para o mundo, libertam-me do mundo onde n\xe3o quero estar e levam-me ao c\xe9u onde o mundo nada \xe9 quando comparado \xe0 sensa\xe7\xe3o de eternidade que sinto quando as escrevo.",
    134: "Todos podemos inspirar o pr\xf3ximo, basta para isso que materializemos em a\xe7\xf5es a nossa verdade.",
    135: "A nossa alma est\xe1 sempre num processo cont\xednuo de evolu\xe7\xe3o, portanto tudo o que contra\xedres e tudo o que conquistares ao longo das tuas vidas fica escrito no teu \xedntimo e \xe9 por isso que vemos nascer, sem explica\xe7\xe3o aparente, tantos medos e tanta coragem em pessoas sem raz\xe3o ou pr\xe1tica de vida suficiente para os terem.",
    136: "A mudan\xe7a implica dor. D\xf3i porque nos obrigamos a romper com padr\xf5es calcinados de conforto e pregui\xe7a onde controlamos e sabemos tudo.",
    137: "Todos temos um passado, mas se desejamos mesmo ser felizes hoje \xe9 preciso saber aceit\xe1-lo, aprender com ele e perdoar-nos.",
    138: "O estar desperto permite-nos passar para al\xe9m da cortina que os olhos alcan\xe7am, extrapolar cren\xe7as limitadoras e mergulhar no vago em que tudo \xe9, tudo existe, tudo verdadeiramente acontece.",
    139: "Somos sempre mais quando escolhemos aceder \xe0 pureza da alma.",
    140: "Algu\xe9m que confie em si \xe9 algu\xe9m que, aconte\xe7a o que acontecer, chegar\xe1 mais longe, conquistar\xe1 mais coisas e inspirar\xe1 mais gente.",
    141: "A vida \xe9 uma constante batalha pelo amor-pr\xf3prio e pelos outros, pelo perd\xe3o e pela aceita\xe7\xe3o. A quest\xe3o \xe9, vais querer viv\xea-la na mesma ou n\xe3o?",
    142: "Abre a tua boca e d\xe1 voz ao teu cora\xe7\xe3o, ele saber\xe1 conduzir-te no texto para que n\xe3o magoes ningu\xe9m e muito menos a ti. Fala.",
    143: "Ningu\xe9m com coisas por dizer se pode sentir verdadeiramente feliz.",
    144: "As palavras que dizemos no dia a dia t\xeam um poder capaz de transformar a nossa vida de um momento para o outro.",
    145: "S\xf3 somos verdadeiramente rejeitados quando rejeitamos a nossa pr\xf3pria verdade. Vamos agir? \xc9 \x93Agora\x94 ou nunca.",
    146: "Cada palavra n\xe3o dita \xe9 um peso que se carrega, \xe9 um pouco de n\xf3s que se perde, \xe9 uma a\xe7\xe3o que n\xe3o tomamos, \xe9 uma vida que n\xe3o temos.",
    147: "Recordar n\xe3o \xe9 viver. Recordar \xe9 deixar de viver. Ningu\xe9m consegue sentir na verdadeira dimens\xe3o da experi\xeancia o que j\xe1 sentiu num outro momento qualquer que n\xe3o seja o \x93Agora\x94.",
    148: "N\xe3o h\xe1 liberdade nem independ\xeancia no medo.",
    149: "\xc9 preponderante viver com a convic\xe7\xe3o de que apenas somos culpados de alguma coisa se agirmos com inten\xe7\xe3o de magoar, caso contr\xe1rio somos apenas respons\xe1veis. N\xe3o, n\xe3o \xe9 a mesma coisa. A culpa sufoca-nos, a responsabilidade empurra-nos para a a\xe7\xe3o e promove a mudan\xe7a.",
    150: "N\xe3o vejas o passado com os olhos com que v\xeas o presente. Na altura n\xe3o eras a pessoa que \xe9s hoje.",
    151: "Nunca te esque\xe7as que n\xe3o conheces a verdadeira hist\xf3ria que est\xe1 por detr\xe1s de quem acusas.",
    152: "O perd\xe3o n\xe3o implica reatar uma rela\xe7\xe3o com algu\xe9m, voltar a partilhar o que quer que seja com essa pessoa ou falar de novo com ela. Perdoar significa um estado de paz sempre que nos lembramos dela, falarem dela ou, eventualmente, se trocarmos olhares com ela.",
    153: "Perdoar n\xe3o \xe9 dif\xedcil. \xc9, ali\xe1s, bastante f\xe1cil quando te amas. \xc9 uma consequ\xeancia normal de quereres sempre o melhor para ti e depois, sem dares conta, torna-se num h\xe1bito.",
    154: "\xc9 bom recordar que somos os \xfanicos respons\xe1veis pela nossa mente, que ningu\xe9m nos tapa a boca e que tudo o que n\xe3o dizemos \xe9 apenas condicionado por n\xf3s, exclusivamente por n\xf3s, pelo medo que cri\xe1mos, pela subvaloriza\xe7\xe3o que nos damos e pela sobrevaloriza\xe7\xe3o que damos aos outros.",
    155: "Sempre que crias depend\xeancia, geras expectativa.",
    156: "O que tu pensas \xe9 t\xe3o valioso como aquilo que eu penso, o que tu achas correto tem o mesmo peso que aquilo que eu acho correto, o que tu argumentas merece o mesmo respeito que aquilo que eu argumento, e a tua verdade pode ser uma mentira para mim ou vice-versa e, apesar disso, nenhuma delas \xe9 mais verdade que a outra.",
    157: "Nada \xe9 mais eterno na nossa cabe\xe7a e na nossa pele que o sabor de um beijo vadio ou a tomada de posse de cum corpo desejado numa noite inesperada. Podem passar-se anos, d\xe9cadas at\xe9, recordar\xe1s sempre aquelas horas como as \xfaltimas da tua vida, pois \xe9 quando perdes o controlo que ganhas lugar na hist\xf3ria.",
    158: "N\xe3o podemos atribuir \xe0 sorte ou ao azar a vida em que vivemos, temos de nos responsabilizar, de olhar bem para dento e perceber a forma como pensamos e posteriormente agimos.",
    159: "Sempre que te ris de algo que j\xe1 te magoou ou te divertes com a repeti\xe7\xe3o de uma situa\xe7\xe3o que j\xe1 te atormentou, d\xe1s a ti mesmo um sinal de que tudo est\xe1 perdoado e que podes seguir em frente.",
    160: "\xc9 lindo quando mergulhas a cabe\xe7a na tua ess\xeancia, quando ouves o que tens para te dizer e \xe9 inesquec\xedvel quando o come\xe7as a materializar.",
    161: "O amor, quando \xe9 amor, n\xe3o precisa de ser correspondido para vencer, basta ser dado incondicionalmente para o ser.",
    162: "Ningu\xe9m est\xe1 apto a dar um passo em frente se nas suas veias n\xe3o correr uma for\xe7a maior, mais capaz e indiferente ao mundo exterior. A for\xe7a interior, mais poderosa e infal\xedvel que qualquer outra base de querer, \xe9 a energia capaz de nos tornar competentes em tudo o que mais desejamos.",
    163: "Viver apegado ao passado \xe9 como respirar por um ventilador, n\xe3o \xe9s tu que o fazes, \xe9 algo ou algu\xe9m que o faz por ti.",
    164: "Mudar \xe9 voltar a sentir, assumir responsabilidades, curar o que h\xe1 para ser tratado e, finalmente, agir.",
    165: "Se respeitares as diferen\xe7as, ficar\xe1s sempre com a sensa\xe7\xe3o de que v\xeas mais longe, alcan\xe7as mais gente e encontras cada vez mais sentido para a tua vida. Eis o perd\xe3o.",
    166: "Nunca conseguiremos alcan\xe7ar a felicidade se ficarmos dependentes de obter dos outros o que n\xe3o conseguimos de n\xf3s pr\xf3prios.",
    167: "Mudar \xe9 t\xe3o precioso como respirar e se n\xe3o o fizermos livremente, a vida encarregar-se-\xe1 de o fazer por n\xf3s, mas de uma forma mais violenta e sem miseric\xf3rdia. \xc9 o pre\xe7o a pagar por nos deixarmos morrer por dentro e desfalecer tudo o que est\xe1 \xe0 nossa volta h\xe1 tanto tempo.",
    168: "Ser espiritual \xe9 saber reconhecer a nossa ess\xeancia, trat\xe1-la bem e obedecer-lhe acima de tudo e de todas as coisas; \xe9 viver o momento, \xe9 a sede de aprender e a humildade quando se ensina, \xe9 sonhar, inspirar e respeitar o que somos.",
    169: "At\xe9 nos encontrarmos, e estaremos sempre em busca de mais de n\xf3s, ca\xedmos muitas vezes, sofremos algumas e quase desistimos umas quantas.",
    170: "Aprendi a caminhar mais forte quando soube que morava em mim uma sabedoria superior, uma voz sempre presente que me impele para a frente, a intui\xe7\xe3o.",
    171: 'As pessoas ao n\xe3o dizerem "N\xe3o" aos outros ficam cada vez mais distantes de dizerem "Sim" a elas mesmas, o mesmo \xe9 dizer que a cada "N\xe3o" sentido e n\xe3o dito se afastam mais de quem verdadeiramente s\xe3o.',
    172: "O corpo \xe9 a estalagem de quem verdadeiramente somos, um aluguer tempor\xe1rio e valioso que nos permite atingir objetivos enquanto seres superiores, mestres e deuses. Permite \xe0 nossa alma chegar \xe0 meta, e por isso devemos cuid\xe1-lo como algo sagrado.",
    173: "A arte de um guerreiro nasce na sua capacidade de persistir, na inigual\xe1vel perseveran\xe7a e na valentia perante quaisquer que sejam as adversidades e os advers\xe1rios.",
    174: "N\xe3o h\xe1 mal-entendidos, n\xe3o h\xe1 d\xfavidas, n\xe3o h\xe1 expectativas, n\xe3o h\xe1 inven\xe7\xf5es nem cria\xe7\xe3o de enredos quando uma pessoa se respeita, \xe9 verdadeira consigo mesma e assertiva para com o mundo.",
    175: "\xc9 fundamental reconheceres a tua import\xe2ncia na tua vida.",
    176: "Acredito na reencarna\xe7\xe3o. N\xe3o admito finais, apenas mudan\xe7a, recome\xe7os e renascimentos.",
    177: "A miss\xe3o da alma vai muito para al\xe9m do papel do corpo e por isso volta constantemente, em diferentes embalagens.",
    178: "A \xfanica companhia que ter\xe1s desde o teu primeiro segundo at\xe9 ao teu \xfaltimo esgar de vida \xe9s tu, como tal, de nada nem ningu\xe9m podes depender a n\xe3o ser de ti. Tudo passa, tu ficas.",
    179: "Um guerreiro veste as suas lutas de paix\xe3o, pois sabe que \xe9 tudo o que precisa para conseguir o que deseja.",
}


TRIGGER_WORDS = {
    "ac\xe7\xe3o": {"last_used_at": datetime.min, "quotes": [45]},
    "ajuda": {"last_used_at": datetime.min, "quotes": [104, 51]},
    "alma": {"last_used_at": datetime.min, "quotes": [177, 139, 135]},
    "amor": {"last_used_at": datetime.min, "quotes": [161, 69, 107, 119, 89, 91, 124, 127],},
    "amor-pr\xf3prio": {"last_used_at": datetime.min, "quotes": [3, 101, 141]},
    "ansiedade": {"last_used_at": datetime.min, "quotes": [90, 12]},
    "auto-confian\xe7a": {
        "last_used_at": datetime.min,
        "quotes": [
            140,
            19,
            21,
            22,
            154,
            28,
            29,
            162,
            36,
            37,
            171,
            174,
            49,
            50,
            52,
            53,
            56,
            61,
            63,
            72,
            77,
            78,
            79,
            80,
            81,
            82,
            85,
            97,
        ],
    },
    "auto-conhecimento": {"last_used_at": datetime.min, "quotes": [129, 39, 8, 46, 175, 54, 153, 125],},
    "auto-estima": {"last_used_at": datetime.min, "quotes": [9, 2, 26]},
    "busca": {"last_used_at": datetime.min, "quotes": [169]},
    "casamento": {"last_used_at": datetime.min, "quotes": [70]},
    "companhia": {"last_used_at": datetime.min, "quotes": [43]},
    "comunica\xe7\xe3o": {"last_used_at": datetime.min, "quotes": [32, 25, 83, 84]},
    "confian\xe7a": {"last_used_at": datetime.min, "quotes": [1]},
    "consci\xeancia": {"last_used_at": datetime.min, "quotes": [87]},
    "cora\xe7\xe3o": {"last_used_at": datetime.min, "quotes": [93, 142]},
    "corpo": {"last_used_at": datetime.min, "quotes": [172]},
    "culpa": {"last_used_at": datetime.min, "quotes": [109, 149]},
    "dar": {"last_used_at": datetime.min, "quotes": [106, 108, 110]},
    "desafio": {"last_used_at": datetime.min, "quotes": [116]},
    "destino": {"last_used_at": datetime.min, "quotes": [11, 4]},
    "dor": {"last_used_at": datetime.min, "quotes": [68]},
    "escolha": {"last_used_at": datetime.min, "quotes": [98, 99]},
    "escrita": {"last_used_at": datetime.min, "quotes": [133]},
    "esp\xedrito": {"last_used_at": datetime.min, "quotes": [168]},
    "expectativa": {"last_used_at": datetime.min, "quotes": [155]},
    "express\xe3o": {"last_used_at": datetime.min, "quotes": [160]},
    "falar": {"last_used_at": datetime.min, "quotes": [33, 38]},
    "felicidade": {"last_used_at": datetime.min, "quotes": [24, 44, 20, 166, 143]},
    "for\xe7a": {"last_used_at": datetime.min, "quotes": [67]},
    "fraternidade": {"last_used_at": datetime.min, "quotes": [128]},
    "futuro": {"last_used_at": datetime.min, "quotes": [10, 13]},
    "h\xe1bito": {"last_used_at": datetime.min, "quotes": [73]},
    "independ\xeancia": {"last_used_at": datetime.min, "quotes": [178]},
    "inspira\xe7\xe3o": {"last_used_at": datetime.min, "quotes": [96, 134]},
    "intui\xe7\xe3o": {"last_used_at": datetime.min, "quotes": [59, 58, 123, 66, 170]},
    "liberdade": {"last_used_at": datetime.min, "quotes": [0]},
    "limite": {"last_used_at": datetime.min, "quotes": [60]},
    "maturidade": {"last_used_at": datetime.min, "quotes": [100]},
    "medita\xe7\xe3o": {"last_used_at": datetime.min, "quotes": [105, 130]},
    "medo": {"last_used_at": datetime.min, "quotes": [148]},
    "mente": {"last_used_at": datetime.min, "quotes": [18]},
    "momento": {"last_used_at": datetime.min, "quotes": [103]},
    "mudan\xe7a": {"last_used_at": datetime.min, "quotes": [164, 167, 136, 41, 74, 176, 115, 122],},
    "mundo": {"last_used_at": datetime.min, "quotes": [118]},
    "opini\xe3o": {"last_used_at": datetime.min, "quotes": [156]},
    "os outros": {"last_used_at": datetime.min, "quotes": [7, 40, 42, 48, 151, 57]},
    "paix\xe3o": {"last_used_at": datetime.min, "quotes": [179, 71]},
    "palavra": {"last_used_at": datetime.min, "quotes": [64, 144, 146]},
    "passado": {"last_used_at": datetime.min, "quotes": [137, 163, 150]},
    "perd\xe3o": {"last_used_at": datetime.min, "quotes": [152, 165, 159]},
    "pergunta": {"last_used_at": datetime.min, "quotes": [92]},
    "perseveran\xe7a": {"last_used_at": datetime.min, "quotes": [173]},
    "personalidade": {"last_used_at": datetime.min, "quotes": [88]},
    "pregui\xe7a": {"last_used_at": datetime.min, "quotes": [55]},
    "presente": {"last_used_at": datetime.min, "quotes": [17, 14, 15]},
    "problema": {"last_used_at": datetime.min, "quotes": [34]},
    "queixa": {"last_used_at": datetime.min, "quotes": [27]},
    "querer": {"last_used_at": datetime.min, "quotes": [117]},
    "recorda\xe7\xe3o": {"last_used_at": datetime.min, "quotes": [147]},
    "rela\xe7\xf5es humanas": {"last_used_at": datetime.min, "quotes": [16, 102]},
    "respeito": {"last_used_at": datetime.min, "quotes": [113]},
    "responsabilidade": {"last_used_at": datetime.min, "quotes": [112, 95]},
    "sociedade": {"last_used_at": datetime.min, "quotes": [132]},
    "solid\xe3o": {"last_used_at": datetime.min, "quotes": [111, 47]},
    "sonho": {"last_used_at": datetime.min, "quotes": [6]},
    "valor": {"last_used_at": datetime.min, "quotes": [126]},
    "velhice": {"last_used_at": datetime.min, "quotes": [120, 121, 114]},
    "verdade": {"last_used_at": datetime.min, "quotes": [145, 30, 23]},
    "vida": {"last_used_at": datetime.min, "quotes": [5, 158]},
    "viver": {"last_used_at": datetime.min, "quotes": [65, 35, 138, 75, 76, 131, 62, 86, 157, 94],},
    "v\xedtima": {"last_used_at": datetime.min, "quotes": [31]},
}
